# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190107_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_auth',
            field=models.BooleanField(default=False),
        ),
    ]
