# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followed', through='accounts.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
