application: vcit-217004
version: 12
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: backend.backend.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'backend.backend.settings'

libraries:
- name: django
  version: '1.11'

- name: MySQLdb
  version: '1.2.5'

- name: ssl
  version: latest
