"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 1.11.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
print ('BASE_DIR ' + BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'unav+(ajsz%h^*1xwb!k0t(1r&5xo6tavrvfiw@%+r-z4(udxf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
Migration = False
ALLOWED_HOSTS = ['*']


# Application definition

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'jjlikesthed'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''


INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'webpack_loader'
]

if Migration:
    INSTALLED_APPS += 'accounts', 'main', 'search_data', 'create_new', 'django.contrib.admin',
    jwt_response_handler = 'backend.utils.my_jwt_response_handler'
    ROOT_URLCONF = 'backend.urls'
else:
    INSTALLED_APPS += 'backend.accounts', 'backend.main', 'backend.search_data', 'backend.create_new',\
                      'django.contrib.admin',
    jwt_response_handler = 'backend.backend.utils.my_jwt_response_handler'
    ROOT_URLCONF = 'backend.backend.urls'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'news',
        'USER': 'root',
        'PASSWORD': 'rondog123',
        'HOST': '/Users/robertoalvarez/Desktop/virtualEnv/news_refactor/cloudsql/vcit-217004:europe-west3:practice1'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

JWT_AUTH = {
    'JWT_VERIFY': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=20),
    'JWT_ALLOW_REFRESH': True,
    'JWT_RESPONSE_PAYLOAD_HANDLER': jwt_response_handler
}

WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundle/',
        'STATS_FILE':(
            os.path.join(BASE_DIR, 'webpack-stats.json')
        ),
    }
}
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
CORS_ORIGIN_WHITELIST = (
    'localhost:8080',
)
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'accounts.User'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATICFILES_DIRS = [
    '/Users/robertoalvarez/Desktop/virtualEnv/news_refactor/app/frontend/dist',
]

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'collectstatic/')
STATIC_ROOT = '/Users/robertoalvarez/Desktop/virtualEnv/news_refactor/app/frontend/dist'

#Monkeypatch required to user requests at app engine
from requests_toolbelt.adapters import appengine
appengine.monkeypatch()