# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-04 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=80)),
                ('bullet_point1', models.CharField(max_length=100, null=True)),
                ('bullet_point2', models.CharField(max_length=100, null=True)),
                ('bullet_point3', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(max_length=605)),
                ('time_stamp', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
